### Health
GET http://localhost:8080/health

### Crear libro
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "book_name": "El principito",
  "book_category": "Infantil",
  "transaction_type": "venta",
  "price": 10000,
  "status": true,
  "stock": 6
}

### Listar libros
GET http://localhost:8080/api/v1/books
